### ISSUE TITLE
Mod Won't Work

### ISSUE THREAD

**Issue by mysterylewds** [NickWildish/Mas-NSFW-Submod#12]
It seems the game recognizes it under the 'Submods' section in the main menu, but the installation prompt Monika is supposed to say never happens. 

I've tried changing numerous things in the rpy files, such as changing the needed affection statuses to 'BROKEN', yet still nothing happens.

Any idea as to what is causing this?

**Comment by mysterylewds** [comment]
Nevermind, I didn't realize just HOW unfinished it was. If you choose to load it, just keep clicking 'ignore'. But yeah, it might and will fuck up your game.

If you guys need help writing dialogue and stuff for this, or artwork, please let me know! I'm open to help making this the best NSFW mod for MAS.

**Comment by NickWildish** [comment]
Sorry for the delay in getting back to you. Yeah the submod is very much unfinished, with placeholder text and all. I was hoping to get back into it sooner but it's been tough to find motivation. However I've now made a Discord server so you guys can pester me for updates as much as you want to get me off my ass and to start working. Here's the link if you're interested: https://discord.gg/YJVKHQj9ru

Otherwise, I'm gonna close this issue.
