### ISSUE TITLE
Bug - Monika's horny level never resets

### ISSUE THREAD

**Issue by TreeWizard96** [NickWildish/Mas-NSFW-Submod#68]
**Describe the bug**
There is no code that resets Monika's horny level after successfully 'finishing' during a sexting session. This means she remains perpetually at her highest state of horniness after the first time. One would assume it should reset back to 0 after completing the sexting event.

Additionally, it should probably decay over time (e.g. -10 points per day) if you end a sexting session early - currently the code applies a flat penalty to her horniness level if you end the session early, but doesn't reset it completely.

**Comment by NickWildish** [comment]
This has been added now in the dev branch, however I would like to leave this issue open for your second point regarding the horny level decaying over time.

**Comment by NickWildish** [comment]
Definitely going to be adding the decay now that the 'finishing early' sections have been polished.
It will probably end up being a case of 'if you don't sext with Monika for 8 hours she resets completely', presumably because she got tired of waiting or her spout of horniness disappeared. That number will be fine-tuned though.

**Comment by NickWildish** [comment]
Added horniness decay after sexting.

Closing issue as resolved.
