### ISSUE TITLE
another error on other girls nsfw stories!

### ISSUE THREAD

**Issue by my-otter-self** [NickWildish/Mas-NSFW-Submod#75]
on first story (natsuki one), as soon as she finishes telling it, she starts all over again from a certain point. 
pic related - history below: 
![image](https://user-images.githubusercontent.com/99370976/175790988-19343f6d-c3cb-4d80-872a-fb78ce6447e8.png)

**Comment by NickWildish** [comment]
Updated release with a fixed version.
The bug was that the event got played twice if it is the first time seeing it (was due to some code that got carried over from when it was an official story).
Please find attached a fixed version that was applied to the release. Let me know if this fixed the issue.
[nsfw_dokistories.zip](https://github.com/NickWildish/Mas-NSFW-Submod/files/8986020/nsfw_dokistories.zip)

**Comment by my-otter-self** [comment]
it did! thank you so much. <3
